export interface LocationItem {
  name: string;
  region: string;
}

export const UZBEKISTAN_REGIONS = [
  'Toshkent shahri',
  'Toshkent viloyati',
  'Samarqand viloyati',
  'Andijon viloyati',
  'Fargʻona viloyati',
  'Namangan viloyati',
  'Buxoro viloyati',
  'Xorazm viloyati',
  'Qashqadaryo viloyati',
  'Surxondaryo viloyati',
  'Jizzax viloyati',
  'Sirdaryo viloyati',
  'Navoiy viloyati',
  'Qoraqalpogʻiston Respublikasi',
] as const;

export const UZBEKISTAN_CITIES_AND_DISTRICTS: LocationItem[] = [
  // --- Toshkent shahri ---
  { name: 'Toshkent (Yunusobod)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Chilonzor)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Mirzo Ulugʻbek)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Yakkasaroy)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Mirobod)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Shayxontohur)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Olmazor)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Uchtepa)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Sergeli)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Yashnobod)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Bektemir)', region: 'Toshkent shahri' },
  { name: 'Toshkent (Yangihayot)', region: 'Toshkent shahri' },

  // --- Toshkent viloyati ---
  { name: 'Chirchiq', region: 'Toshkent viloyati' },
  { name: 'Olmaliq', region: 'Toshkent viloyati' },
  { name: 'Angren', region: 'Toshkent viloyati' },
  { name: 'Bekobod', region: 'Toshkent viloyati' },
  { name: 'Nurafshon', region: 'Toshkent viloyati' },
  { name: 'Yangiyoʻl', region: 'Toshkent viloyati' },
  { name: 'Boʻstonliq (Chorvoq/Gʻazalkent)', region: 'Toshkent viloyati' },
  { name: 'Zangiota', region: 'Toshkent viloyati' },
  { name: 'Qibray', region: 'Toshkent viloyati' },
  { name: 'Parkent', region: 'Toshkent viloyati' },
  { name: 'Toshkent tumani (Keles)', region: 'Toshkent viloyati' },
  { name: 'Oqqoʻrgʻon', region: 'Toshkent viloyati' },
  { name: 'Chinoz', region: 'Toshkent viloyati' },
  { name: 'Yuqori Chirchiq', region: 'Toshkent viloyati' },
  { name: 'Oʻrta Chirchiq', region: 'Toshkent viloyati' },
  { name: 'Quyi Chirchiq', region: 'Toshkent viloyati' },
  { name: 'Piskent', region: 'Toshkent viloyati' },
  { name: 'Boʻka', region: 'Toshkent viloyati' },

  // --- Samarqand viloyati ---
  { name: 'Samarqand shahri', region: 'Samarqand viloyati' },
  { name: 'Kattaqoʻrgʻon shahri', region: 'Samarqand viloyati' },
  { name: 'Urgut', region: 'Samarqand viloyati' },
  { name: 'Bulungʻur', region: 'Samarqand viloyati' },
  { name: 'Jomboy', region: 'Samarqand viloyati' },
  { name: 'Ishtixon', region: 'Samarqand viloyati' },
  { name: 'Oqdaryo (Loyish)', region: 'Samarqand viloyati' },
  { name: 'Pastdargʻom (Juma)', region: 'Samarqand viloyati' },
  { name: 'Payariq (Chelak)', region: 'Samarqand viloyati' },
  { name: 'Samarqand tumani', region: 'Samarqand viloyati' },
  { name: 'Toyloq', region: 'Samarqand viloyati' },
  { name: 'Narpay (Oqtosh)', region: 'Samarqand viloyati' },
  { name: 'Paxtachi (Ziyovuddin)', region: 'Samarqand viloyati' },
  { name: 'Qoʻshrabot', region: 'Samarqand viloyati' },
  { name: 'Nurobod', region: 'Samarqand viloyati' },

  // --- Andijon viloyati ---
  { name: 'Andijon shahri', region: 'Andijon viloyati' },
  { name: 'Xonobod shahri', region: 'Andijon viloyati' },
  { name: 'Asaka', region: 'Andijon viloyati' },
  { name: 'Shahrixon', region: 'Andijon viloyati' },
  { name: 'Qoʻrgʻontepa', region: 'Andijon viloyati' },
  { name: 'Oltinkoʻl', region: 'Andijon viloyati' },
  { name: 'Baliqchi', region: 'Andijon viloyati' },
  { name: 'Boʻston (Boʻz)', region: 'Andijon viloyati' },
  { name: 'Buloqboshi', region: 'Andijon viloyati' },
  { name: 'Izboskan (Poytugʻ)', region: 'Andijon viloyati' },
  { name: 'Jalaquduq (Oxunboboyev)', region: 'Andijon viloyati' },
  { name: 'Marhamat', region: 'Andijon viloyati' },
  { name: 'Paxtaobod', region: 'Andijon viloyati' },
  { name: 'Ulugʻnor (Oqoltin)', region: 'Andijon viloyati' },
  { name: 'Xoʻjaobod', region: 'Andijon viloyati' },

  // --- Fargʻona viloyati ---
  { name: 'Fargʻona shahri', region: 'Fargʻona viloyati' },
  { name: 'Qoʻqon shahri', region: 'Fargʻona viloyati' },
  { name: 'Margʻilon shahri', region: 'Fargʻona viloyati' },
  { name: 'Quvasoy shahri', region: 'Fargʻona viloyati' },
  { name: 'Quva', region: 'Fargʻona viloyati' },
  { name: 'Oltiariq', region: 'Fargʻona viloyati' },
  { name: 'Rishton', region: 'Fargʻona viloyati' },
  { name: 'Beshariq', region: 'Fargʻona viloyati' },
  { name: 'Bogʻdod', region: 'Fargʻona viloyati' },
  { name: 'Buvayda (Ibrat)', region: 'Fargʻona viloyati' },
  { name: 'Dangʻara', region: 'Fargʻona viloyati' },
  { name: 'Fargʻona tumani (Vodil)', region: 'Fargʻona viloyati' },
  { name: 'Furqat (Navbahor)', region: 'Fargʻona viloyati' },
  { name: 'Qoʻshtepa (Langar)', region: 'Fargʻona viloyati' },
  { name: 'Soʻx (Ravon)', region: 'Fargʻona viloyati' },
  { name: 'Toshloq', region: 'Fargʻona viloyati' },
  { name: 'Uchkoʻprik', region: 'Fargʻona viloyati' },
  { name: 'Yozyovon', region: 'Fargʻona viloyati' },

  // --- Namangan viloyati ---
  { name: 'Namangan shahri', region: 'Namangan viloyati' },
  { name: 'Chust', region: 'Namangan viloyati' },
  { name: 'Kosonsoy', region: 'Namangan viloyati' },
  { name: 'Pop', region: 'Namangan viloyati' },
  { name: 'Toʻraqoʻrgʻon', region: 'Namangan viloyati' },
  { name: 'Uchqoʻrgʻon', region: 'Namangan viloyati' },
  { name: 'Chortoq', region: 'Namangan viloyati' },
  { name: 'Norin (Haqqulobod)', region: 'Namangan viloyati' },
  { name: 'Mingbuloq (Jomashoʻy)', region: 'Namangan viloyati' },
  { name: 'Uychi', region: 'Namangan viloyati' },
  { name: 'Yangiqoʻrgʻon', region: 'Namangan viloyati' },
  { name: 'Davlatobod tumani', region: 'Namangan viloyati' },
  { name: 'Yangi Namangan tumani', region: 'Namangan viloyati' },

  // --- Buxoro viloyati ---
  { name: 'Buxoro shahri', region: 'Buxoro viloyati' },
  { name: 'Kogon shahri', region: 'Buxoro viloyati' },
  { name: 'Gʻijduvon', region: 'Buxoro viloyati' },
  { name: 'Vobkent', region: 'Buxoro viloyati' },
  { name: 'Jondor', region: 'Buxoro viloyati' },
  { name: 'Kogon tumani', region: 'Buxoro viloyati' },
  { name: 'Olot', region: 'Buxoro viloyati' },
  { name: 'Peshku (Yangibozor)', region: 'Buxoro viloyati' },
  { name: 'Qorakoʻl', region: 'Buxoro viloyati' },
  { name: 'Qorovulbozor', region: 'Buxoro viloyati' },
  { name: 'Romitan', region: 'Buxoro viloyati' },
  { name: 'Shofirkon', region: 'Buxoro viloyati' },
  { name: 'Buxoro tumani (Galaosiyo)', region: 'Buxoro viloyati' },

  // --- Xorazm viloyati ---
  { name: 'Urganch shahri', region: 'Xorazm viloyati' },
  { name: 'Xiva shahri', region: 'Xorazm viloyati' },
  { name: 'Xonka', region: 'Xorazm viloyati' },
  { name: 'Bogʻot', region: 'Xorazm viloyati' },
  { name: 'Gurlan', region: 'Xorazm viloyati' },
  { name: 'Qoʻshkoʻpir', region: 'Xorazm viloyati' },
  { name: 'Shovot', region: 'Xorazm viloyati' },
  { name: 'Tuproqqalʼa (Pitnak)', region: 'Xorazm viloyati' },
  { name: 'Xazorasp', region: 'Xorazm viloyati' },
  { name: 'Yangiariq', region: 'Xorazm viloyati' },
  { name: 'Yangibozor', region: 'Xorazm viloyati' },

  // --- Qashqadaryo viloyati ---
  { name: 'Qarshi shahri', region: 'Qashqadaryo viloyati' },
  { name: 'Shahrisabz shahri', region: 'Qashqadaryo viloyati' },
  { name: 'Kitob', region: 'Qashqadaryo viloyati' },
  { name: 'Koson', region: 'Qashqadaryo viloyati' },
  { name: 'Gʻuzor', region: 'Qashqadaryo viloyati' },
  { name: 'Qamashi', region: 'Qashqadaryo viloyati' },
  { name: 'Kasbi (Mugʻlon)', region: 'Qashqadaryo viloyati' },
  { name: 'Mirishkor (Yangi Mirishkor)', region: 'Qashqadaryo viloyati' },
  { name: 'Muborak', region: 'Qashqadaryo viloyati' },
  { name: 'Nishon (Yangi Nishon)', region: 'Qashqadaryo viloyati' },
  { name: 'Chiroqchi', region: 'Qashqadaryo viloyati' },
  { name: 'Koʻkdala (Yettitom)', region: 'Qashqadaryo viloyati' },
  { name: 'Dehqonobod (Karashina)', region: 'Qashqadaryo viloyati' },
  { name: 'Yakkabogʻ', region: 'Qashqadaryo viloyati' },

  // --- Surxondaryo viloyati ---
  { name: 'Termiz shahri', region: 'Surxondaryo viloyati' },
  { name: 'Denov', region: 'Surxondaryo viloyati' },
  { name: 'Sherobod', region: 'Surxondaryo viloyati' },
  { name: 'Boysun', region: 'Surxondaryo viloyati' },
  { name: 'Jarqoʻrgʻon', region: 'Surxondaryo viloyati' },
  { name: 'Qumqoʻrgʻon', region: 'Surxondaryo viloyati' },
  { name: 'Shoʻrchi', region: 'Surxondaryo viloyati' },
  { name: 'Sariosiyo', region: 'Surxondaryo viloyati' },
  { name: 'Uzun', region: 'Surxondaryo viloyati' },
  { name: 'Oltinsoy (Qarluq)', region: 'Surxondaryo viloyati' },
  { name: 'Angor', region: 'Surxondaryo viloyati' },
  { name: 'Bandixon', region: 'Surxondaryo viloyati' },
  { name: 'Muzrabot (Xalqobod)', region: 'Surxondaryo viloyati' },
  { name: 'Qiziriq (Sariq)', region: 'Surxondaryo viloyati' },
  { name: 'Termiz tumani (Uchqizil)', region: 'Surxondaryo viloyati' },

  // --- Jizzax viloyati ---
  { name: 'Jizzax shahri', region: 'Jizzax viloyati' },
  { name: 'Zomin', region: 'Jizzax viloyati' },
  { name: 'Gʻallaorol', region: 'Jizzax viloyati' },
  { name: 'Baxmal (Usmat)', region: 'Jizzax viloyati' },
  { name: 'Doʻstlik', region: 'Jizzax viloyati' },
  { name: 'Zarbdor', region: 'Jizzax viloyati' },
  { name: 'Zafarobod', region: 'Jizzax viloyati' },
  { name: 'Mirzachoʻl (Gagarin)', region: 'Jizzax viloyati' },
  { name: 'Paxtakor', region: 'Jizzax viloyati' },
  { name: 'Forish (Yangiqishloq)', region: 'Jizzax viloyati' },
  { name: 'Sharof Rashidov tumani (Uchtepa)', region: 'Jizzax viloyati' },
  { name: 'Arnasoy (Gʻoliblar)', region: 'Jizzax viloyati' },
  { name: 'Yangiobod (Balandchaqir)', region: 'Jizzax viloyati' },

  // --- Sirdaryo viloyati ---
  { name: 'Guliston shahri', region: 'Sirdaryo viloyati' },
  { name: 'Shirin shahri', region: 'Sirdaryo viloyati' },
  { name: 'Yangiyer shahri', region: 'Sirdaryo viloyati' },
  { name: 'Boyovut', region: 'Sirdaryo viloyati' },
  { name: 'Guliston tumani (Dehqonobod)', region: 'Sirdaryo viloyati' },
  { name: 'Mirzaobod (Navroʻz)', region: 'Sirdaryo viloyati' },
  { name: 'Oqoltin (Sardoba)', region: 'Sirdaryo viloyati' },
  { name: 'Sayxunobod (Sayxun)', region: 'Sirdaryo viloyati' },
  { name: 'Sardoba (Paxtaobod)', region: 'Sirdaryo viloyati' },
  { name: 'Sirdaryo tumani', region: 'Sirdaryo viloyati' },
  { name: 'Xovos', region: 'Sirdaryo viloyati' },

  // --- Navoiy viloyati ---
  { name: 'Navoiy shahri', region: 'Navoiy viloyati' },
  { name: 'Zarafshon shahri', region: 'Navoiy viloyati' },
  { name: 'Qiziltepa', region: 'Navoiy viloyati' },
  { name: 'Karmana', region: 'Navoiy viloyati' },
  { name: 'Konimex', region: 'Navoiy viloyati' },
  { name: 'Navbahor (Beshrabot)', region: 'Navoiy viloyati' },
  { name: 'Nurota', region: 'Navoiy viloyati' },
  { name: 'Tomdi (Tomdibuloq)', region: 'Navoiy viloyati' },
  { name: 'Uchquduq', region: 'Navoiy viloyati' },
  { name: 'Xatirchi (Yangirabot)', region: 'Navoiy viloyati' },

  // --- Qoraqalpogʻiston Respublikasi ---
  { name: 'Nukus shahri', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Beruniy', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Toʻrtkoʻl', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Xoʻjayli', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Amudaryo (Mangʻit)', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Chimboy', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Ellikqalʼa (Boʻston)', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Kegeyli', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Moʻynoq', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Nukus tumani (Oqmangʻit)', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Qanlikoʻl (Leninobod)', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Qoʻngʻirot', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Qoraoʻzak', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Shumanay', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Taxtakoʻpir', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Taxiatosh shahri', region: 'Qoraqalpogʻiston Respublikasi' },
  { name: 'Boʻzatov', region: 'Qoraqalpogʻiston Respublikasi' },
];
